// Deterministic markdown projection of a FeatureSpec. Pure: same input,
// same output — the .md is regenerated on every render and never read back.
import type { FeatureSpec } from "./spec-schema.ts";

export function renderSpecMd(spec: FeatureSpec, priority: number): string {
  const dep = spec.dependsOn.length ? spec.dependsOn.join(", ") : "—";
  const src = spec.source.lines
    ? `${spec.source.file}:${spec.source.lines}`
    : spec.source.file;
  const outScope = spec.scope.outOfScope.length
    ? spec.scope.outOfScope.map((s) => `- ${s}`)
    : ["- —"];

  const lines: string[] = [
    `# ${spec.featureId}: ${spec.title}`,
    "",
    `> **Module:** ${spec.module} · **Priority:** ${priority}/100 · **Depends on:** ${dep} · **Source:** ${src}`,
    "",
    spec.description,
    "",
    "## Scope",
    "",
    "**In:**",
    ...spec.scope.inScope.map((s) => `- ${s}`),
    "",
    "**Out:**",
    ...outScope,
    "",
    "## Acceptance Criteria",
    "",
    ...spec.acceptanceCriteria.map(
      (ac) => `- [${ac.done ? "x" : " "}] **${ac.id}** — ${ac.text}`
    ),
    "",
    "---",
    "",
    "## Mulai kerja",
    "",
    "1. Jalankan `superpowers:brainstorming` dengan file ini sebagai starting point —",
    "   scope & AC di atas adalah requirement; task breakdown dan pilihan teknis",
    "   diputuskan di sesi brainstorming (dengan akses codebase).",
    "2. Setelah implementasi, centang tiap AC yang sudah terbukti jalan",
    `   (update \`done\` di \`${spec.featureId}.json\`, lalu jalankan ulang render-specs).`,
    "3. Setelah semua AC tercentang, tandai fitur selesai di registry:",
    `   \`/prep --done ${spec.featureId} [commit-sha ...]\` — ini yang menghapus`,
    "   fitur dari feature-queue aktif dan membuatnya muncul sebagai shipped di /status.",
    "",
    `_Generated by /prep — edit \`${spec.featureId}.json\`, bukan file ini (akan di-overwrite)._`,
    "",
  ];
  return lines.join("\n");
}
