import type {
  PrdDoc,
  UserFlowsDoc,
  TechNotesDoc,
  ClientQuestionsDoc,
} from "./order-schemas.js";

const mark = (c: string): string => `\`[${c}]\``;
const today = (): string => new Date().toISOString().split("T")[0];

// --- Changelog (deterministic JSON diff) ---

function isObj(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function diffOrderDoc(prev: unknown, next: unknown, path = ""): string[] {
  const changes: string[] = [];
  if (Array.isArray(prev) && Array.isArray(next)) {
    const max = Math.max(prev.length, next.length);
    for (let i = 0; i < max; i++) {
      const p = `${path}[${i}]`;
      if (i >= prev.length) changes.push(`added ${p}`);
      else if (i >= next.length) changes.push(`removed ${p}`);
      else changes.push(...diffOrderDoc(prev[i], next[i], p));
    }
  } else if (isObj(prev) && isObj(next)) {
    const keys = new Set([...Object.keys(prev), ...Object.keys(next)]);
    for (const k of keys) {
      const p = path ? `${path}.${k}` : k;
      if (!(k in prev)) changes.push(`added ${p}`);
      else if (!(k in next)) changes.push(`removed ${p}`);
      else changes.push(...diffOrderDoc(prev[k], next[k], p));
    }
  } else if (JSON.stringify(prev) !== JSON.stringify(next)) {
    changes.push(`changed ${path || "(root)"}`);
  }
  return changes;
}

export function renderChangelog(changes: string[]): string {
  if (changes.length === 0) return "";
  return ["", "## Changes since last run", ...changes.map((c) => `- ${c}`), ""].join("\n");
}

function withChangelog<T>(body: string, doc: T, prev?: T): string {
  if (!prev) return body;
  const log = renderChangelog(diffOrderDoc(prev, doc));
  return log ? `${body}\n${log}\n` : body;
}

// --- Renderers ---

export function renderPrd(doc: PrdDoc): string {
  const overview = doc.projectState.hasExistingCodebase
    ? `${doc.overview} This work builds on an existing codebase.`
    : `${doc.overview} This is a greenfield build with no existing codebase to integrate with.`;

  const lines: string[] = [
    `# ${doc.projectName} — Product Requirements Document`,
    "",
    `## Overview`,
    overview,
    "",
    `## Actors`,
    ...doc.actors.map((a) => `- ${a.name} — ${a.role}`),
    "",
    `## Modules & Features`,
    ...doc.modules.flatMap((m) => [
      `### ${m.name}`,
      m.description,
      "",
      ...m.features.map((f) => `- ${f.text}`),
      "",
    ]),
    `## Integrations`,
    ...(doc.integrations.length ? doc.integrations.map((i) => `- ${i.text}`) : ["_None._"]),
    "",
    `## Constraints`,
    ...(doc.constraints.length ? doc.constraints.map((c) => `- ${c.text}`) : ["_None._"]),
    "",
    `## Stakeholders`,
    ...(doc.stakeholders.length
      ? doc.stakeholders.map((s) => `- ${s.name} — ${s.role}`)
      : ["_Identify during client kickoff._"]),
    "",
    `## Timeline`,
    doc.timeline ?? "Not specified",
    "",
    `## Open Questions`,
    `${doc.openQuestionsCount} questions remain — see \`client-questions.md\``,
    "",
  ];
  return lines.join("\n");
}

function renderStepFields(step: UserFlowsDoc["flows"][number]["steps"][number]): string[] {
  if (!step.fields || step.fields.length === 0) return [];
  return step.fields.map((f) => {
    const opts = f.options && f.options.length ? `: ${f.options.join(", ")}` : "";
    return `   - ${f.name} (${f.type}${f.required ? ", required" : ""})${opts}`;
  });
}

export function renderUserFlows(doc: UserFlowsDoc, prev?: UserFlowsDoc): string {
  const lines: string[] = [
    `# User Flows`,
    "",
    `> Generated by sandwich/order · ${today()}`,
    "",
    ...doc.flows.flatMap((f) => [
      `### ${f.id} — ${f.title}`,
      `- **Actor:** ${f.actor}`,
      `- **Trigger:** ${f.trigger}`,
      `- **Needs UI:** ${f.needsUI ? "yes" : "no"}`,
      `- **Confidence:** ${mark(f.confidence)}`,
      "",
      `**Steps:**`,
      ...f.steps.flatMap((s, i) => [`${i + 1}. ${s.text}`, ...renderStepFields(s)]),
      "",
      `**Outcome:** ${f.outcome}`,
      "",
    ]),
  ];
  return withChangelog(lines.join("\n"), doc, prev);
}

export function renderTechNotes(doc: TechNotesDoc, prev?: TechNotesDoc): string {
  const lines: string[] = [
    `# Technical Notes`,
    "",
    `> Generated by sandwich/order · ${today()}`,
    "",
    `## Stack`,
    ...(doc.stack.length
      ? [
          `| Layer | Choice | Rationale |`,
          `|-------|--------|-----------|`,
          ...doc.stack.map((s) => `| ${s.layer} | ${s.choice} | ${s.rationale} |`),
        ]
      : ["_Not specified._"]),
    "",
    `## Architecture Notes`,
    ...(doc.architectureNotes.length
      ? doc.architectureNotes.flatMap((a) => [`### ${a.heading}`, a.body, ""])
      : ["_None._", ""]),
    `## Risks`,
    ...(doc.risks.length
      ? doc.risks.map((r) => `- **[${r.severity}]** ${r.text}`)
      : ["_None identified._"]),
    "",
    `## Open Decisions`,
    ...(doc.openDecisions.length
      ? doc.openDecisions.map((d) => `- ${mark(d.confidence)} ${d.text}`)
      : ["_None._"]),
    "",
  ];
  return withChangelog(lines.join("\n"), doc, prev);
}

export function renderClientQuestions(doc: ClientQuestionsDoc, prev?: ClientQuestionsDoc): string {
  const lines: string[] = [
    `# Client Questions`,
    "",
    `> Generated by sandwich/order · ${today()}`,
    "",
    ...(doc.questions.length
      ? doc.questions.flatMap((q) => [
          `### ${q.id} (${q.priority})`,
          q.question,
          "",
          `- **Why:** ${q.why}`,
          `- **Blocks:** ${q.blocks.length ? q.blocks.join(", ") : "—"}`,
          "",
        ])
      : ["_No open questions._", ""]),
  ];
  return withChangelog(lines.join("\n"), doc, prev);
}
